// Temporary mock service
export const fetchRecords = async () => {
  return Promise.resolve([
    {
      id: 1,
      tagProduct: "TP001",
      definition: "Sample Product A",
      storeOrd: 120,
      storeRec: 115,
      storeRet: 5,
      storeSal: 90,
      storeStr: 10,
      storeTro: 3,
      storeTri: 2,
      dcOrd: 200,
      dcRec: 190,
      dcRet: 4,
      dcTro: 5,
      dcTri: 1,
      itemType: "Electronics",
    },
    {
      id: 2,
      tagProduct: "TP002",
      definition: "Sample Product B",
      storeOrd: 80,
      storeRec: 75,
      storeRet: 2,
      storeSal: 60,
      storeStr: 5,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 150,
      dcRec: 140,
      dcRet: 3,
      dcTro: 2,
      dcTri: 0,
      itemType: "Furniture",
    },
    {
      id: 3,
      tagProduct: "TP003",
      definition: "Sample Product C",
      storeOrd: 200,
      storeRec: 198,
      storeRet: 1,
      storeSal: 150,
      storeStr: 20,
      storeTro: 4,
      storeTri: 3,
      dcOrd: 300,
      dcRec: 295,
      dcRet: 2,
      dcTro: 1,
      dcTri: 2,
      itemType: "Clothing",
    },
  ]);
};
