// Temporary mock service
export const fetchRecords = async () => {
  return Promise.resolve([
    {
      id: 1,
      tagProduct: "TP001",
      definition: "Sample Product A",
      storeOrd: 120,
      storeRec: 115,
      storeRet: 5,
      storeSal: 90,
      storeStr: 10,
      storeTro: 3,
      storeTri: 2,
      dcOrd: 200,
      dcRec: 190,
      dcRet: 4,
      dcTro: 5,
      dcTri: 1,
      itemType: "Electronics",
    },
    {
      id: 2,
      tagProduct: "TP002",
      definition: "Sample Product B",
      storeOrd: 80,
      storeRec: 75,
      storeRet: 2,
      storeSal: 60,
      storeStr: 5,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 150,
      dcRec: 140,
      dcRet: 3,
      dcTro: 2,
      dcTri: 0,
      itemType: "Furniture",
    },
    {
      id: 3,
      tagProduct: "TP003",
      definition: "Sample Product C",
      storeOrd: 200,
      storeRec: 198,
      storeRet: 1,
      storeSal: 150,
      storeStr: 20,
      storeTro: 4,
      storeTri: 3,
      dcOrd: 300,
      dcRec: 295,
      dcRet: 2,
      dcTro: 1,
      dcTri: 2,
      itemType: "Clothing",
    },
    {
      id: 4,
      tagProduct: "TP004",
      definition: "Sample Product D",
      storeOrd: 60,
      storeRec: 58,
      storeRet: 1,
      storeSal: 50,
      storeStr: 3,
      storeTro: 2,
      storeTri: 0,
      dcOrd: 100,
      dcRec: 98,
      dcRet: 0,
      dcTro: 1,
      dcTri: 0,
      itemType: "Toys",
    },
    {
      id: 5,
      tagProduct: "TP005",
      definition: "Sample Product E",
      storeOrd: 95,
      storeRec: 90,
      storeRet: 3,
      storeSal: 70,
      storeStr: 6,
      storeTro: 2,
      storeTri: 1,
      dcOrd: 160,
      dcRec: 155,
      dcRet: 2,
      dcTro: 1,
      dcTri: 0,
      itemType: "Appliances",
    },
    {
      id: 6,
      tagProduct: "TP006",
      definition: "Sample Product F",
      storeOrd: 150,
      storeRec: 145,
      storeRet: 2,
      storeSal: 120,
      storeStr: 10,
      storeTro: 3,
      storeTri: 2,
      dcOrd: 250,
      dcRec: 245,
      dcRet: 1,
      dcTro: 2,
      dcTri: 0,
      itemType: "Books",
    },
    {
      id: 7,
      tagProduct: "TP007",
      definition: "Sample Product G",
      storeOrd: 45,
      storeRec: 43,
      storeRet: 0,
      storeSal: 30,
      storeStr: 2,
      storeTro: 0,
      storeTri: 0,
      dcOrd: 80,
      dcRec: 78,
      dcRet: 0,
      dcTro: 1,
      dcTri: 0,
      itemType: "Stationery",
    },
    {
      id: 8,
      tagProduct: "TP008",
      definition: "Sample Product H",
      storeOrd: 300,
      storeRec: 295,
      storeRet: 5,
      storeSal: 250,
      storeStr: 20,
      storeTro: 10,
      storeTri: 5,
      dcOrd: 500,
      dcRec: 490,
      dcRet: 6,
      dcTro: 4,
      dcTri: 2,
      itemType: "Sports",
    },
    {
      id: 9,
      tagProduct: "TP009",
      definition: "Sample Product I",
      storeOrd: 110,
      storeRec: 108,
      storeRet: 1,
      storeSal: 95,
      storeStr: 5,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 180,
      dcRec: 175,
      dcRet: 2,
      dcTro: 1,
      dcTri: 0,
      itemType: "Electronics",
    },
    {
      id: 10,
      tagProduct: "TP010",
      definition: "Sample Product J",
      storeOrd: 75,
      storeRec: 72,
      storeRet: 2,
      storeSal: 55,
      storeStr: 4,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 130,
      dcRec: 128,
      dcRet: 1,
      dcTro: 1,
      dcTri: 0,
      itemType: "Furniture",
    },
    {
      id: 11,
      tagProduct: "TP011",
      definition: "Sample Product K",
      storeOrd: 130,
      storeRec: 127,
      storeRet: 2,
      storeSal: 100,
      storeStr: 8,
      storeTro: 2,
      storeTri: 1,
      dcOrd: 220,
      dcRec: 215,
      dcRet: 2,
      dcTro: 2,
      dcTri: 1,
      itemType: "Appliances",
    },
    {
      id: 12,
      tagProduct: "TP012",
      definition: "Sample Product L",
      storeOrd: 95,
      storeRec: 92,
      storeRet: 1,
      storeSal: 70,
      storeStr: 5,
      storeTro: 1,
      storeTri: 1,
      dcOrd: 150,
      dcRec: 147,
      dcRet: 2,
      dcTro: 1,
      dcTri: 0,
      itemType: "Clothing",
    },
    {
      id: 13,
      tagProduct: "TP013",
      definition: "Sample Product M",
      storeOrd: 170,
      storeRec: 165,
      storeRet: 3,
      storeSal: 140,
      storeStr: 10,
      storeTro: 4,
      storeTri: 2,
      dcOrd: 280,
      dcRec: 275,
      dcRet: 3,
      dcTro: 2,
      dcTri: 1,
      itemType: "Electronics",
    },
    {
      id: 14,
      tagProduct: "TP014",
      definition: "Sample Product N",
      storeOrd: 65,
      storeRec: 62,
      storeRet: 1,
      storeSal: 50,
      storeStr: 3,
      storeTro: 0,
      storeTri: 0,
      dcOrd: 100,
      dcRec: 98,
      dcRet: 1,
      dcTro: 1,
      dcTri: 0,
      itemType: "Stationery",
    },
    {
      id: 15,
      tagProduct: "TP015",
      definition: "Sample Product O",
      storeOrd: 210,
      storeRec: 205,
      storeRet: 4,
      storeSal: 180,
      storeStr: 12,
      storeTro: 3,
      storeTri: 2,
      dcOrd: 350,
      dcRec: 345,
      dcRet: 2,
      dcTro: 2,
      dcTri: 1,
      itemType: "Furniture",
    },
    {
      id: 16,
      tagProduct: "TP016",
      definition: "Sample Product P",
      storeOrd: 140,
      storeRec: 138,
      storeRet: 1,
      storeSal: 110,
      storeStr: 7,
      storeTro: 2,
      storeTri: 1,
      dcOrd: 230,
      dcRec: 228,
      dcRet: 1,
      dcTro: 1,
      dcTri: 0,
      itemType: "Toys",
    },
    {
      id: 17,
      tagProduct: "TP017",
      definition: "Sample Product Q",
      storeOrd: 55,
      storeRec: 53,
      storeRet: 0,
      storeSal: 40,
      storeStr: 3,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 90,
      dcRec: 88,
      dcRet: 0,
      dcTro: 0,
      dcTri: 0,
      itemType: "Books",
    },
    {
      id: 18,
      tagProduct: "TP018",
      definition: "Sample Product R",
      storeOrd: 185,
      storeRec: 180,
      storeRet: 2,
      storeSal: 160,
      storeStr: 10,
      storeTro: 3,
      storeTri: 2,
      dcOrd: 300,
      dcRec: 295,
      dcRet: 2,
      dcTro: 1,
      dcTri: 1,
      itemType: "Clothing",
    },
    {
      id: 19,
      tagProduct: "TP019",
      definition: "Sample Product S",
      storeOrd: 75,
      storeRec: 73,
      storeRet: 1,
      storeSal: 60,
      storeStr: 4,
      storeTro: 1,
      storeTri: 0,
      dcOrd: 120,
      dcRec: 118,
      dcRet: 1,
      dcTro: 0,
      dcTri: 0,
      itemType: "Appliances",
    },
    {
      id: 20,
      tagProduct: "TP020",
      definition: "Sample Product T",
      storeOrd: 160,
      storeRec: 155,
      storeRet: 3,
      storeSal: 130,
      storeStr: 9,
      storeTro: 2,
      storeTri: 1,
      dcOrd: 260,
      dcRec: 255,
      dcRet: 2,
      dcTro: 2,
      dcTri: 1,
      itemType: "Sports",
    },
  ]);
};
